# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sol < Formula
  desc "Multi-agent orchestration system"
  homepage "https://github.com/nevinsm/sol"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nevinsm/sol/releases/download/v0.1.0/sol_0.1.0_darwin_amd64.tar.gz"
      sha256 "0e73e0e0a3fa2a937ad59c189c54e8e608bdd4e7aa5e521a2e9ea08e4d4c0de7"

      define_method(:install) do
        bin.install "sol"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nevinsm/sol/releases/download/v0.1.0/sol_0.1.0_darwin_arm64.tar.gz"
      sha256 "97cc2d43339839d997fb8f2e1f12dc0d000c376f1958272111276c75851b038e"

      define_method(:install) do
        bin.install "sol"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nevinsm/sol/releases/download/v0.1.0/sol_0.1.0_linux_amd64.tar.gz"
      sha256 "c73bcdb87f672fc251ec10db7389d94efe70fc895dbad0af0535d318806c7b61"
      define_method(:install) do
        bin.install "sol"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nevinsm/sol/releases/download/v0.1.0/sol_0.1.0_linux_arm64.tar.gz"
      sha256 "58e48560509ade6f2e5b9c6585fd380990399ec3f5aa3d642c73dfe21bc8f947"
      define_method(:install) do
        bin.install "sol"
      end
    end
  end

  test do
    system bin/"sol", "version"
  end
end
