# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sol < Formula
  desc "Multi-agent orchestration system"
  homepage "https://github.com/nevinsm/sol"
  version "0.1.0"
  license "MIT"

  depends_on "git"
  depends_on "jq"
  depends_on "tmux"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nevinsm/sol/releases/download/v0.1.0/sol_0.1.0_darwin_amd64.tar.gz"
      sha256 "1d41bd55ce75afeb2d723f178fade2d6d98b240aabe409855374b023af75ba84"

      define_method(:install) do
        bin.install "sol"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nevinsm/sol/releases/download/v0.1.0/sol_0.1.0_darwin_arm64.tar.gz"
      sha256 "cfae735f808000630cb0aec37c1175108c2be6ec2d94cf4c5beab67ddea50d5f"

      define_method(:install) do
        bin.install "sol"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nevinsm/sol/releases/download/v0.1.0/sol_0.1.0_linux_amd64.tar.gz"
      sha256 "4ec9b6ded55a339df16035956c35fad5ab45e490e27f92639935109f7a829c9c"
      define_method(:install) do
        bin.install "sol"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nevinsm/sol/releases/download/v0.1.0/sol_0.1.0_linux_arm64.tar.gz"
      sha256 "85d58c5b8719dbab033b57bd1e2c93c5d49e8c05630ba45b7ce4cf0cb3766bcf"
      define_method(:install) do
        bin.install "sol"
      end
    end
  end

  test do
    system bin/"sol", "version"
  end
end
