# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sol < Formula
  desc "Multi-agent orchestration system"
  homepage "https://github.com/nevinsm/sol"
  version "0.1.0"
  license "MIT"

  depends_on "tmux"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nevinsm/sol/releases/download/v0.1.0/sol_0.1.0_darwin_amd64.tar.gz"
      sha256 "aa240819b1f5a1caa2e773bf4c477a9fe3d3aa9aa817ed1f35d3ea851aea8b51"

      define_method(:install) do
        bin.install "sol"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nevinsm/sol/releases/download/v0.1.0/sol_0.1.0_darwin_arm64.tar.gz"
      sha256 "722adbdabfb311411fb0c60f7f5dceb920dc793cddd6628544343d2468ee5745"

      define_method(:install) do
        bin.install "sol"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nevinsm/sol/releases/download/v0.1.0/sol_0.1.0_linux_amd64.tar.gz"
      sha256 "71c17d1ec224c41a3c53c4d84d67976295fd2944c6ac04da9ed73c905d3053cc"
      define_method(:install) do
        bin.install "sol"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nevinsm/sol/releases/download/v0.1.0/sol_0.1.0_linux_arm64.tar.gz"
      sha256 "68158ac16d0b1d93098b6104ae1ea0c951373fedb488f5f3795e728395e7e55f"
      define_method(:install) do
        bin.install "sol"
      end
    end
  end

  test do
    system bin/"sol", "version"
  end
end
