# This file was generated by GoReleaser. DO NOT EDIT.
cask "sol" do
  version "0.3.1"

  on_macos do
    on_intel do
      url "https://github.com/nevinsm/sol/releases/download/v#{version}/sol_#{version}_darwin_amd64.tar.gz"
      sha256 "a96bd82d602eb52f2f350d5aa397a7164c1b2791fa6fa55343eacc80552fe428"
    end
    on_arm do
      url "https://github.com/nevinsm/sol/releases/download/v#{version}/sol_#{version}_darwin_arm64.tar.gz"
      sha256 "35c5852f2ed43e684f839c307d68ca210602c3608e7b2427d7eb648d04491b45"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/nevinsm/sol/releases/download/v#{version}/sol_#{version}_linux_amd64.tar.gz"
      sha256 "bab15be228d84ccdc41991d0365bcb10d58d1c3d564aa08cecf376dcf3bb2c5a"
    end
    on_arm do
      url "https://github.com/nevinsm/sol/releases/download/v#{version}/sol_#{version}_linux_arm64.tar.gz"
      sha256 "dde40c47ff3359df90ee613addc34066a18b93da41c6209ebf2b4e6a8e4f7e38"
    end
  end

  name "sol"
  desc "Multi-agent orchestration system"
  homepage "https://github.com/nevinsm/sol"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sol"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/sol"]
    end
  end

  # No zap stanza required

end
