# This file was generated by GoReleaser. DO NOT EDIT.
cask "sol" do
  version "0.2.0"

  on_macos do
    on_intel do
      url "https://github.com/nevinsm/sol/releases/download/v#{version}/sol_#{version}_darwin_amd64.tar.gz"
      sha256 "d9711fd9b6e10d3ffa8ae9d2e11e299e7a97408dbe748e89bd6e29d659c13213"
    end
    on_arm do
      url "https://github.com/nevinsm/sol/releases/download/v#{version}/sol_#{version}_darwin_arm64.tar.gz"
      sha256 "32c82e61a59e20391988e20d0fb5a5250e629323818f2509bfd5acf926472944"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/nevinsm/sol/releases/download/v#{version}/sol_#{version}_linux_amd64.tar.gz"
      sha256 "d5a54d82b6933132f83cba38dd944309f41e358780e6394b9052ea940491ede4"
    end
    on_arm do
      url "https://github.com/nevinsm/sol/releases/download/v#{version}/sol_#{version}_linux_arm64.tar.gz"
      sha256 "807ef2d3e0dc7e683d1c15cfee85fbbb1757d5c77e079ebc9f0965431fa00660"
    end
  end

  name "sol"
  desc "Multi-agent orchestration system"
  homepage "https://github.com/nevinsm/sol"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sol"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/sol"]
    end
  end

  # No zap stanza required

end
