# This file was generated by GoReleaser. DO NOT EDIT.
cask "sol" do
  version "0.3.6"

  on_macos do
    on_intel do
      sha256 "fd97fefbf846a947d6a094e93f7df11097a2a8c49e9eccf1b6eecf575e022657"
      url "https://github.com/nevinsm/sol/releases/download/v#{version}/sol_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "54ba26ebd7ad03fc0ff3d6a0971399585e6e4a1593411855298c3a99c28dc5c5"
      url "https://github.com/nevinsm/sol/releases/download/v#{version}/sol_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e9e9c99ec1cd7ce9a2485ce467559fe21505f3356271e8b4d8b5b99f96fd2975"
      url "https://github.com/nevinsm/sol/releases/download/v#{version}/sol_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1c2c5a0ab8c1ce5b5c1097b187a868f9bcf99c5c5a38f55020c702bdefbc5a06"
      url "https://github.com/nevinsm/sol/releases/download/v#{version}/sol_#{version}_linux_arm64.tar.gz"
    end
  end

  name "sol"
  desc "Multi-agent orchestration system"
  homepage "https://github.com/nevinsm/sol"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sol"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/sol"]
    end
  end

  # No zap stanza required

end
